-- 1. Автоматическая генерация значения ID (Автоинкремент, Serial)
create table person
(
    id    int GENERATED BY DEFAULT AS IDENTITY,
    name  varchar,
    age   int,
    email varchar
);

-- 2. Ограничения (Constraints) - NOT NULL, UNIQUE, PRIMARY KEY, CHECK
create table person
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar NOT NULL,
    age   int CHECK (age > 0),
    email varchar UNIQUE
);

alter table person add column address varchar not null default 'some address';


--2. Кастомные запросы в Spring Data JPA
create table item
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int          references person (id) on delete set null,
    item_name varchar(100) not null
);

truncate person restart identity cascade;
insert into person(name, age, email, address)
values ('Tom', 25, 'tom@gmail.com', 'Tom, Tom, 123456'),
       ('Bob', 31, 'bob1@gmail.com', 'Bob1, Bob1, 123456'),
       ('Bob', 53, 'bob2@gmail.com', 'Bob2, Bob2, 123456'),
       ('Bob', 20, 'bob3@gmail.com', 'Bob2, Bob2, 123456'),
       ('Katy', 14, 'katy@gmail.com', 'Tom, Tom, 123456');

insert into item(person_id, item_name)
values (4, 'Item1'),
       (4, 'Item2'),
       (4, 'TV');